/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface LzSideDraw {
    'title': string;
  }
  interface LzSideDrawAttributes extends StencilHTMLAttributes {
    'title'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'LzSideDraw': Components.LzSideDraw;
  }

  interface StencilIntrinsicElements {
    'lz-side-draw': Components.LzSideDrawAttributes;
  }


  interface HTMLLzSideDrawElement extends Components.LzSideDraw, HTMLStencilElement {}
  var HTMLLzSideDrawElement: {
    prototype: HTMLLzSideDrawElement;
    new (): HTMLLzSideDrawElement;
  };

  interface HTMLElementTagNameMap {
    'lz-side-draw': HTMLLzSideDrawElement
  }

  interface ElementTagNameMap {
    'lz-side-draw': HTMLLzSideDrawElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
